# vim: ft=mconf
# example windigo configuration file

# this config is mconf, see more about the syntax at https://github.com/marzeq/mconf

# this is where you define human readable names for your devices
devices = {
  # use either
  # - name:(name of the device in /sys/class/hwmon/hwmon*/name), make sure the name is unique, in some cases there might be multiple devices with the same name
  # - hwmon:X for the device in /sys/class/hwmon/hwmonX, although this might change across reboots
  # - pci:XX:XX.X for the device in /sys/bus/pci/devices/0000:XX:XX.X
  # - pci:XXXX:XX:XX.X for the device in /sys/bus/pci/devices/XXXX:XX:XX.X
  "name:k10temp" = CPU
  "name:it8689" = Motherboard
  "pci:03:00.0" = GPU
}

# this is where you define human readable names for your sensors
sensors = {
  # this is the device name in the devices section
  CPU = {
    # this is the sensor filename in /sys/class/hwmon/hwmonX/device/ or similar
    # important: the the tempetature output must be in milidegrees Celsius
    temp1_input = CPU
  }

  GPU = {
    temp1_input = GPU
  }
}

# this is where you define human readable names for your fans
curves = {
  curve1 = { # this is the name of the curve
    # a curve can be either steps or linear
    # if it's steps, the points mean "from this point onwards, use this fan speed"
    # if it's linear, the fan speed is calculated using linear interpolation
    type = step
    sensor = CPU # the human readable name of the sensor in the sensors section
    points = [ # [temperature, fan %]
      [0, 25],
      [60, 50],
      [70, 80],
      [100, 100]
    ]
    hysteresis = 0 # by how many degrees the temperature must fall/rise before the fan speed is reduced/increased (float/int)
    period = 3 # how often to read the temperature in seconds (int)
  }

  # this is an example "flat" curve, where the fan speed is constant
  # we achieve it by using a step curve with only one point starting at 0C
  max = {
    type = step
    sensors = ["CPU", "GPU"] # you can use multiple sensors for the same curve
    aggregate = max # can be min, max or avg (default: avg)
    points = [
      [0, 100]
    ]
  }
}

# a feature of mconf where you can define constants
$current_curve = curve1

# this is where you define the fans and which curve they should use
fans = {
  Motherboard = { # this is the device name in the devices section
    "CPU fans" = { # this is the human readable name of the fan
      curve = $current_curve # the human readable name of the curve in the curves section (in this case, it points to whatever current_curve is set to)

      inputfile = pwm1 # the filename in /sys/class/hwmon/hwmonX/device/ or similar
      enablefile = pwm1_enable # the filename in /sys/class/hwmon/hwmonX/device/ or similar
      readfile = fan1_input # the filename in /sys/class/hwmon/hwmonX/device/ or similar
      # these files should all have the same number and in 99.99% of the cases, they are pwmX, pwmX_enable and fanX_input
      # if not, they are probably not supported by windigo
    }

    "Case fans" = {
      curve = $current_curve

      inputfile = pwm2
      enablefile = pwm2_enable
      readfile = fan2_input
    }
  }
}
